# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
gems:                [jekyll-paginate]
paginate_path:       "page:num"

# Setup
title:               Cameron's blog
tagline:             ' about software, programming, and sorcery'
description:         'There are a lot of dev blogs out there. This is just another one.'
url:                 http://emptyflash.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Cameron Alexander
  url:               https://twitter.com/SoftwareWarlock
  email:             emptyflash@gmail.com

# Custom vars
version:             1.0.0
